name: Erlang CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: erlang:22.0.7
        steps:
            - uses: actions/checkout@v2
            - name: Release
              run: make release
            - name: Tests
              run: make test
            - name: Analysis
              run: make analysis
